<?php
return [
    "locales" => [
      'en' => [
        'carbonformat' => 'n/d/Y',
        'carbonformattime' => 'n/d/Y h:i A',
        'carbonformattimeseconds' => 'n/d/Y h:i:s A',
        'formatdisplay' => 'M/DD/YYYY',
        'formatdisplaytime' => 'M/DD/YYYY hh:mm A',
        'formatdisplaytimeseconds' => 'M/DD/YYYY hh:mm:ss A',
        'showISOWeekNumbers' =>  true,
        'firstday' => 0
      ],
      "fr" => [
        'carbonformat' => 'd/m/Y',
        'carbonformattime' => 'd/m/Y H:i',
        'carbonformattimeseconds' => 'd/m/Y H:i:s',
        'formatdisplay' => 'DD/MM/YYYY',
        'formatdisplaytime' => 'DD/MM/YYYY HH:mm',
        'formatdisplaytimeseconds' => 'DD/MM/YYYY HH:mm:ss',
        'showISOWeekNumbers' =>  true,
        'firstday' => 1

      ],
    ],
    'default' => [
        'icon' => '<i class="fas fa-calendar-alt"></i>',
        "opens" => 'right',
        "drops" => 'auto',
        'maxSpan' => '',
        'maxYear' => 0,
        'minYear' => 0,
        'usehiddeninputs' => true,
        'hiddeninputstart' => '',
        'hiddeninputend' => '',
        'hiddensingleinput' => '',
        'submitfunction' => '',
        'momentinputdate' => 'YYYY-MM-DD',
        'momentinputdatetime' => 'YYYY-MM-DD HH:mm:ss',
        'carboninputdate' => 'Y-m-d',
        'carboninputdatetime' => 'Y-m-d H:i:s',
        "showDropdowns" => false,
        'timePicker' => false,
        'timePicker24Hour' => true,
        "timePickerSeconds" => false,
        "timePickerIncrement" => 1,
        'dateseparator' => ' - ',
        'firstday' => 1,
        'autoApply' => false,
        'daysofweek' => [
            '#daterangepickerhelper::messages.day0#',
            '#daterangepickerhelper::messages.day1#',
            '#daterangepickerhelper::messages.day2#',
            '#daterangepickerhelper::messages.day3#',
            '#daterangepickerhelper::messages.day4#',
            '#daterangepickerhelper::messages.day5#',
            '#daterangepickerhelper::messages.day6#',
        ],
        'monthnames' => [
           '#daterangepickerhelper::messages.month01#',
           '#daterangepickerhelper::messages.month02#',
           '#daterangepickerhelper::messages.month03#',
           '#daterangepickerhelper::messages.month04#',
           '#daterangepickerhelper::messages.month05#',
           '#daterangepickerhelper::messages.month06#',
           '#daterangepickerhelper::messages.month07#',
            '#daterangepickerhelper::messages.month08#',
            '#daterangepickerhelper::messages.month09#',
            '#daterangepickerhelper::messages.month10#' ,
            '#daterangepickerhelper::messages.month11#',
            '#daterangepickerhelper::messages.month12#',
        ],
        'ranges' => [
          '#daterangepickerhelper::messages.today#' =>  ['moment()', 'moment()'],
          '#daterangepickerhelper::messages.yesterday#' => ["moment().subtract(1, 'days')", "moment().subtract(1, 'days')"],
          '#daterangepickerhelper::messages.last7d#' => ["moment().subtract(6, 'days')", "moment()"],
          '#daterangepickerhelper::messages.last30d#' => ["moment().subtract(29, 'days')", "moment()"],
          '#daterangepickerhelper::messages.thismonth#' => ["moment().startOf('month')", "moment().endOf('month')"],
          '#daterangepickerhelper::messages.lastmonth#' => ["moment().subtract(1, 'month').startOf('month')", "moment().subtract(1, 'month').endOf('month')"],
        ],
        'applylabel' =>  '#daterangepickerhelper::messages.applylabel#',
        'cancellabel' =>  '#daterangepickerhelper::messages.cancellabel#',
        'fromlabel' =>  '#daterangepickerhelper::messages.fromlabel#',
        'tolabel'   =>  '#daterangepickerhelper::messages.tolabel#',
        'customrange' =>  '#daterangepickerhelper::messages.customrange#',
        'weeklabel' => '#daterangepickerhelper::messages.weeklabel#',
        'singleDatePicker' =>  false,
        "formdivclass" => 'mb-3',
        'formlabel' => '',
        'formlabelclass' => 'control-label',
        'alwaysShowCalendars' => true,
        "caldivclass" => "cal-selector",
        "buttonClasses" => "",
        "applyButtonClasses" => "",
        "cancelButtonClasses" => "",
        "showCustomRangeLabel" => true,
        'linkedCalendars' => false,
        'showISOWeekNumbers' =>  false,
        'showWeekNumbers' => false,
        "show.daterangepicker" => '',
        "hide.daterangepicker" => '',
        "showCalendar.daterangepicker" => '',
        "hideCalendar.daterangepicker" => '',
        "apply.daterangepicker" => '',
        "cancel.daterangepicker" => '',
    ]
];
